-- adds FIPS data to the zip/state/county table

ALTER TABLE `zipcode` ADD COLUMN `FipsCode` VARCHAR(5) NOT NULL AFTER `County`;

update zipcode set FipsCode = '1' where ucase(County) = 'ADAMS';
update zipcode set FipsCode = '3' where ucase(County) = 'ALEXANDER';
update zipcode set FipsCode = '5' where ucase(County) = 'BOND';
update zipcode set FipsCode = '7' where ucase(County) = 'BOONE';
update zipcode set FipsCode = '9' where ucase(County) = 'BROWN';
update zipcode set FipsCode = '11' where ucase(County) = 'BUREAU';
update zipcode set FipsCode = '13' where ucase(County) = 'CALHOUN';
update zipcode set FipsCode = '15' where ucase(County) = 'CARROLL';
update zipcode set FipsCode = '17' where ucase(County) = 'CASS';
update zipcode set FipsCode = '19' where ucase(County) = 'CHAMPAIGN';
update zipcode set FipsCode = '21' where ucase(County) = 'CHRISTIAN';
update zipcode set FipsCode = '23' where ucase(County) = 'CLARK';
update zipcode set FipsCode = '25' where ucase(County) = 'CLAY';
update zipcode set FipsCode = '27' where ucase(County) = 'CLINTON';
update zipcode set FipsCode = '29' where ucase(County) = 'COLES';
update zipcode set FipsCode = '31' where ucase(County) = 'COOK';
update zipcode set FipsCode = '33' where ucase(County) = 'CRAWFORD';
update zipcode set FipsCode = '35' where ucase(County) = 'CUMBERLAND';
update zipcode set FipsCode = '39' where ucase(County) = 'DE WITT';
update zipcode set FipsCode = '39' where ucase(County) = 'DEWITT';
update zipcode set FipsCode = '37' where ucase(County) = 'DEKALB';
update zipcode set FipsCode = '41' where ucase(County) = 'DOUGLAS';
update zipcode set FipsCode = '43' where ucase(County) = 'DUPAGE';
update zipcode set FipsCode = '45' where ucase(County) = 'EDGAR';
update zipcode set FipsCode = '47' where ucase(County) = 'EDWARDS';
update zipcode set FipsCode = '49' where ucase(County) = 'EFFINGHAM';
update zipcode set FipsCode = '51' where ucase(County) = 'FAYETTE';
update zipcode set FipsCode = '53' where ucase(County) = 'FORD';
update zipcode set FipsCode = '55' where ucase(County) = 'FRANKLIN';
update zipcode set FipsCode = '57' where ucase(County) = 'FULTON';
update zipcode set FipsCode = '59' where ucase(County) = 'GALLATIN';
update zipcode set FipsCode = '61' where ucase(County) = 'GREENE';
update zipcode set FipsCode = '63' where ucase(County) = 'GRUNDY';
update zipcode set FipsCode = '65' where ucase(County) = 'HAMILTON';
update zipcode set FipsCode = '67' where ucase(County) = 'HANCOCK';
update zipcode set FipsCode = '69' where ucase(County) = 'HARDIN';
update zipcode set FipsCode = '71' where ucase(County) = 'HENDERSON';
update zipcode set FipsCode = '73' where ucase(County) = 'HENRY';
update zipcode set FipsCode = '75' where ucase(County) = 'IROQUOIS';
update zipcode set FipsCode = '77' where ucase(County) = 'JACKSON';
update zipcode set FipsCode = '79' where ucase(County) = 'JASPER';
update zipcode set FipsCode = '81' where ucase(County) = 'JEFFERSON';
update zipcode set FipsCode = '83' where ucase(County) = 'JERSEY';
update zipcode set FipsCode = '85' where ucase(County) = 'JO DAVIESS';
update zipcode set FipsCode = '87' where ucase(County) = 'JOHNSON';
update zipcode set FipsCode = '89' where ucase(County) = 'KANE';
update zipcode set FipsCode = '91' where ucase(County) = 'KANKAKEE';
update zipcode set FipsCode = '93' where ucase(County) = 'KENDALL';
update zipcode set FipsCode = '95' where ucase(County) = 'KNOX';
update zipcode set FipsCode = '99' where ucase(County) = 'LA SALLE';
update zipcode set FipsCode = '97' where ucase(County) = 'LAKE';
update zipcode set FipsCode = '101' where ucase(County) = 'LAWRENCE';
update zipcode set FipsCode = '103' where ucase(County) = 'LEE';
update zipcode set FipsCode = '105' where ucase(County) = 'LIVINGSTON';
update zipcode set FipsCode = '107' where ucase(County) = 'LOGAN';
update zipcode set FipsCode = '115' where ucase(County) = 'MACON';
update zipcode set FipsCode = '117' where ucase(County) = 'MACOUPIN';
update zipcode set FipsCode = '119' where ucase(County) = 'MADISON';
update zipcode set FipsCode = '121' where ucase(County) = 'MARION';
update zipcode set FipsCode = '123' where ucase(County) = 'MARSHALL';
update zipcode set FipsCode = '125' where ucase(County) = 'MASON';
update zipcode set FipsCode = '127' where ucase(County) = 'MASSAC';
update zipcode set FipsCode = '109' where ucase(County) = 'MCDONOUGH';
update zipcode set FipsCode = '111' where ucase(County) = 'MCHENRY';
update zipcode set FipsCode = '113' where ucase(County) = 'MCLEAN';
update zipcode set FipsCode = '129' where ucase(County) = 'MENARD';
update zipcode set FipsCode = '131' where ucase(County) = 'MERCER';
update zipcode set FipsCode = '133' where ucase(County) = 'MONROE';
update zipcode set FipsCode = '135' where ucase(County) = 'MONTGOMERY';
update zipcode set FipsCode = '137' where ucase(County) = 'MORGAN';
update zipcode set FipsCode = '139' where ucase(County) = 'MOULTRIE';
update zipcode set FipsCode = '141' where ucase(County) = 'OGLE';
update zipcode set FipsCode = '143' where ucase(County) = 'PEORIA';
update zipcode set FipsCode = '145' where ucase(County) = 'PERRY';
update zipcode set FipsCode = '147' where ucase(County) = 'PIATT';
update zipcode set FipsCode = '149' where ucase(County) = 'PIKE';
update zipcode set FipsCode = '151' where ucase(County) = 'POPE';
update zipcode set FipsCode = '153' where ucase(County) = 'PULASKI';
update zipcode set FipsCode = '155' where ucase(County) = 'PUTNAM';
update zipcode set FipsCode = '157' where ucase(County) = 'RANDOLPH';
update zipcode set FipsCode = '159' where ucase(County) = 'RICHLAND';
update zipcode set FipsCode = '161' where ucase(County) = 'ROCK ISLAND';
update zipcode set FipsCode = '163' where ucase(County) = 'SAINT CLAIR';
update zipcode set FipsCode = '165' where ucase(County) = 'SALINE';
update zipcode set FipsCode = '167' where ucase(County) = 'SANGAMON';
update zipcode set FipsCode = '169' where ucase(County) = 'SCHUYLER';
update zipcode set FipsCode = '171' where ucase(County) = 'SCOTT';
update zipcode set FipsCode = '173' where ucase(County) = 'SHELBY';
update zipcode set FipsCode = '163' where ucase(County) = 'ST. CLAIR';
update zipcode set FipsCode = '175' where ucase(County) = 'STARK';
update zipcode set FipsCode = '177' where ucase(County) = 'STEPHENSON';
update zipcode set FipsCode = '179' where ucase(County) = 'TAZEWELL';
update zipcode set FipsCode = '181' where ucase(County) = 'UNION';
update zipcode set FipsCode = '183' where ucase(County) = 'VERMILION';
update zipcode set FipsCode = '185' where ucase(County) = 'WABASH';
update zipcode set FipsCode = '187' where ucase(County) = 'WARREN';
update zipcode set FipsCode = '189' where ucase(County) = 'WASHINGTON';
update zipcode set FipsCode = '191' where ucase(County) = 'WAYNE';
update zipcode set FipsCode = '193' where ucase(County) = 'WHITE';
update zipcode set FipsCode = '195' where ucase(County) = 'WHITESIDE';
update zipcode set FipsCode = '197' where ucase(County) = 'WILL';
update zipcode set FipsCode = '199' where ucase(County) = 'WILLIAMSON';
update zipcode set FipsCode = '201' where ucase(County) = 'WINNEBAGO';
update zipcode set FipsCode = '203' where ucase(County) = 'WOODFORD';

update zipcode set FipsCode = lpad(FipsCode,3, '0');

update system_setting set ss_data='007' where ss_code='VERSION';