//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.3603.
// 
#pragma warning disable 1591

namespace AffinityClient.AffinityServer {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WsProcessorSoap", Namespace="http://www.affinityistitle.com/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Loadable))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(object[]))]
    public partial class WsProcessor : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AuthenticateOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetNewRequestsOperationCompleted;
        
        private System.Threading.SendOrPostCallback SyncRequestOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WsProcessor() {
            this.Url = global::AffinityClient.Properties.Settings.Default.AffinityClient_localhost_WsProcessor;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AuthenticateCompletedEventHandler AuthenticateCompleted;
        
        /// <remarks/>
        public event GetNewRequestsCompletedEventHandler GetNewRequestsCompleted;
        
        /// <remarks/>
        public event SyncRequestCompletedEventHandler SyncRequestCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.affinityistitle.com/Authenticate", RequestNamespace="http://www.affinityistitle.com/", ResponseNamespace="http://www.affinityistitle.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public WsToken Authenticate(string username, string password) {
            object[] results = this.Invoke("Authenticate", new object[] {
                        username,
                        password});
            return ((WsToken)(results[0]));
        }
        
        /// <remarks/>
        public void AuthenticateAsync(string username, string password) {
            this.AuthenticateAsync(username, password, null);
        }
        
        /// <remarks/>
        public void AuthenticateAsync(string username, string password, object userState) {
            if ((this.AuthenticateOperationCompleted == null)) {
                this.AuthenticateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAuthenticateOperationCompleted);
            }
            this.InvokeAsync("Authenticate", new object[] {
                        username,
                        password}, this.AuthenticateOperationCompleted, userState);
        }
        
        private void OnAuthenticateOperationCompleted(object arg) {
            if ((this.AuthenticateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AuthenticateCompleted(this, new AuthenticateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.affinityistitle.com/GetNewRequests", RequestNamespace="http://www.affinityistitle.com/", ResponseNamespace="http://www.affinityistitle.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] GetNewRequests(WsToken token) {
            object[] results = this.Invoke("GetNewRequests", new object[] {
                        token});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void GetNewRequestsAsync(WsToken token) {
            this.GetNewRequestsAsync(token, null);
        }
        
        /// <remarks/>
        public void GetNewRequestsAsync(WsToken token, object userState) {
            if ((this.GetNewRequestsOperationCompleted == null)) {
                this.GetNewRequestsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetNewRequestsOperationCompleted);
            }
            this.InvokeAsync("GetNewRequests", new object[] {
                        token}, this.GetNewRequestsOperationCompleted, userState);
        }
        
        private void OnGetNewRequestsOperationCompleted(object arg) {
            if ((this.GetNewRequestsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetNewRequestsCompleted(this, new GetNewRequestsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.affinityistitle.com/SyncRequest", RequestNamespace="http://www.affinityistitle.com/", ResponseNamespace="http://www.affinityistitle.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public WsResponse SyncRequest(WsToken token, System.Xml.XmlNode doc) {
            object[] results = this.Invoke("SyncRequest", new object[] {
                        token,
                        doc});
            return ((WsResponse)(results[0]));
        }
        
        /// <remarks/>
        public void SyncRequestAsync(WsToken token, System.Xml.XmlNode doc) {
            this.SyncRequestAsync(token, doc, null);
        }
        
        /// <remarks/>
        public void SyncRequestAsync(WsToken token, System.Xml.XmlNode doc, object userState) {
            if ((this.SyncRequestOperationCompleted == null)) {
                this.SyncRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSyncRequestOperationCompleted);
            }
            this.InvokeAsync("SyncRequest", new object[] {
                        token,
                        doc}, this.SyncRequestOperationCompleted, userState);
        }
        
        private void OnSyncRequestOperationCompleted(object arg) {
            if ((this.SyncRequestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SyncRequestCompleted(this, new SyncRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.affinityistitle.com/")]
    public partial class WsToken {
        
        private string usernameField;
        
        private string sessionIdField;
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string SessionId {
            get {
                return this.sessionIdField;
            }
            set {
                this.sessionIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.affinityistitle.com/")]
    public partial class WsResponse {
        
        private bool isSuccessField;
        
        private bool actionWasTakenField;
        
        private string messageField;
        
        private bool notificationSentField;
        
        private string notificationMessageField;
        
        /// <remarks/>
        public bool IsSuccess {
            get {
                return this.isSuccessField;
            }
            set {
                this.isSuccessField = value;
            }
        }
        
        /// <remarks/>
        public bool ActionWasTaken {
            get {
                return this.actionWasTakenField;
            }
            set {
                this.actionWasTakenField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public bool NotificationSent {
            get {
                return this.notificationSentField;
            }
            set {
                this.notificationSentField = value;
            }
        }
        
        /// <remarks/>
        public string NotificationMessage {
            get {
                return this.notificationMessageField;
            }
            set {
                this.notificationMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Request))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Order))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Account))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Company))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Role))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.affinityistitle.com/")]
    public abstract partial class Loadable {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.affinityistitle.com/")]
    public partial class Request : Loadable {
        
        private int idField;
        
        private string requestTypeCodeField;
        
        private int orderIdField;
        
        private int originatorIdField;
        
        private System.DateTime createdField;
        
        private string statusCodeField;
        
        private string xmlField;
        
        private bool isCurrentField;
        
        private string noteField;
        
        private Order orderField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string RequestTypeCode {
            get {
                return this.requestTypeCodeField;
            }
            set {
                this.requestTypeCodeField = value;
            }
        }
        
        /// <remarks/>
        public int OrderId {
            get {
                return this.orderIdField;
            }
            set {
                this.orderIdField = value;
            }
        }
        
        /// <remarks/>
        public int OriginatorId {
            get {
                return this.originatorIdField;
            }
            set {
                this.originatorIdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Created {
            get {
                return this.createdField;
            }
            set {
                this.createdField = value;
            }
        }
        
        /// <remarks/>
        public string StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Xml {
            get {
                return this.xmlField;
            }
            set {
                this.xmlField = value;
            }
        }
        
        /// <remarks/>
        public bool IsCurrent {
            get {
                return this.isCurrentField;
            }
            set {
                this.isCurrentField = value;
            }
        }
        
        /// <remarks/>
        public string Note {
            get {
                return this.noteField;
            }
            set {
                this.noteField = value;
            }
        }
        
        /// <remarks/>
        public Order Order {
            get {
                return this.orderField;
            }
            set {
                this.orderField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.affinityistitle.com/")]
    public partial class Order : Loadable {
        
        private int idField;
        
        private string internalIdField;
        
        private string customerIdField;
        
        private string pinField;
        
        private string additionalPinsField;
        
        private string propertyAddressField;
        
        private string propertyAddress2Field;
        
        private string propertyCityField;
        
        private string propertyStateField;
        
        private string propertyZipField;
        
        private string propertyCountyField;
        
        private string internalStatusCodeField;
        
        private string customerStatusCodeField;
        
        private int originatorIdField;
        
        private System.DateTime createdField;
        
        private System.DateTime modifiedField;
        
        private System.DateTime closingDateField;
        
        private string clientNameField;
        
        private Account accountField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string InternalId {
            get {
                return this.internalIdField;
            }
            set {
                this.internalIdField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerId {
            get {
                return this.customerIdField;
            }
            set {
                this.customerIdField = value;
            }
        }
        
        /// <remarks/>
        public string Pin {
            get {
                return this.pinField;
            }
            set {
                this.pinField = value;
            }
        }
        
        /// <remarks/>
        public string AdditionalPins {
            get {
                return this.additionalPinsField;
            }
            set {
                this.additionalPinsField = value;
            }
        }
        
        /// <remarks/>
        public string PropertyAddress {
            get {
                return this.propertyAddressField;
            }
            set {
                this.propertyAddressField = value;
            }
        }
        
        /// <remarks/>
        public string PropertyAddress2 {
            get {
                return this.propertyAddress2Field;
            }
            set {
                this.propertyAddress2Field = value;
            }
        }
        
        /// <remarks/>
        public string PropertyCity {
            get {
                return this.propertyCityField;
            }
            set {
                this.propertyCityField = value;
            }
        }
        
        /// <remarks/>
        public string PropertyState {
            get {
                return this.propertyStateField;
            }
            set {
                this.propertyStateField = value;
            }
        }
        
        /// <remarks/>
        public string PropertyZip {
            get {
                return this.propertyZipField;
            }
            set {
                this.propertyZipField = value;
            }
        }
        
        /// <remarks/>
        public string PropertyCounty {
            get {
                return this.propertyCountyField;
            }
            set {
                this.propertyCountyField = value;
            }
        }
        
        /// <remarks/>
        public string InternalStatusCode {
            get {
                return this.internalStatusCodeField;
            }
            set {
                this.internalStatusCodeField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerStatusCode {
            get {
                return this.customerStatusCodeField;
            }
            set {
                this.customerStatusCodeField = value;
            }
        }
        
        /// <remarks/>
        public int OriginatorId {
            get {
                return this.originatorIdField;
            }
            set {
                this.originatorIdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Created {
            get {
                return this.createdField;
            }
            set {
                this.createdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Modified {
            get {
                return this.modifiedField;
            }
            set {
                this.modifiedField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ClosingDate {
            get {
                return this.closingDateField;
            }
            set {
                this.closingDateField = value;
            }
        }
        
        /// <remarks/>
        public string ClientName {
            get {
                return this.clientNameField;
            }
            set {
                this.clientNameField = value;
            }
        }
        
        /// <remarks/>
        public Account Account {
            get {
                return this.accountField;
            }
            set {
                this.accountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.affinityistitle.com/")]
    public partial class Account : Loadable {
        
        private int idField;
        
        private string usernameField;
        
        private string passwordField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string statusCodeField;
        
        private System.DateTime createdField;
        
        private System.DateTime modifiedField;
        
        private string passwordHintField;
        
        private string preferencesXmlField;
        
        private string roleCodeField;
        
        private int companyIdField;
        
        private string internalIdField;
        
        private string emailField;
        
        private string underwriterCodesField;
        
        private string underwriterEndorsementsField;

        private Company companyField;
        
        private Role roleField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Created {
            get {
                return this.createdField;
            }
            set {
                this.createdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Modified {
            get {
                return this.modifiedField;
            }
            set {
                this.modifiedField = value;
            }
        }
        
        /// <remarks/>
        public string PasswordHint {
            get {
                return this.passwordHintField;
            }
            set {
                this.passwordHintField = value;
            }
        }
        
        /// <remarks/>
        public string PreferencesXml {
            get {
                return this.preferencesXmlField;
            }
            set {
                this.preferencesXmlField = value;
            }
        }
        
        /// <remarks/>
        public string RoleCode {
            get {
                return this.roleCodeField;
            }
            set {
                this.roleCodeField = value;
            }
        }
        
        /// <remarks/>
        public int CompanyId {
            get {
                return this.companyIdField;
            }
            set {
                this.companyIdField = value;
            }
        }
        
        /// <remarks/>
        public string InternalId {
            get {
                return this.internalIdField;
            }
            set {
                this.internalIdField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string UnderwriterCodes {
            get {
                return this.underwriterCodesField;
            }
            set {
                this.underwriterCodesField = value;
            }
        }
        
        /// <remarks/>
				public string UnderwriterEndorsements {
            get {
				return this.underwriterEndorsementsField;
            }
            set {
				this.underwriterEndorsementsField = value;
            }
        }
        
        /// <remarks/>
        public Company Company {
            get {
                return this.companyField;
            }
            set {
                this.companyField = value;
            }
        }
        
        /// <remarks/>
        public Role Role {
            get {
                return this.roleField;
            }
            set {
                this.roleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.affinityistitle.com/")]
    public partial class Company : Loadable {
        
        private int idField;
        
        private string nameField;
        
        private System.DateTime createdField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Created {
            get {
                return this.createdField;
            }
            set {
                this.createdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.affinityistitle.com/")]
    public partial class Role : Loadable {
        
        private string codeField;
        
        private string descriptionField;
        
        private int permissionBitField;
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public int PermissionBit {
            get {
                return this.permissionBitField;
            }
            set {
                this.permissionBitField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void AuthenticateCompletedEventHandler(object sender, AuthenticateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AuthenticateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AuthenticateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WsToken Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WsToken)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void GetNewRequestsCompletedEventHandler(object sender, GetNewRequestsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetNewRequestsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetNewRequestsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void SyncRequestCompletedEventHandler(object sender, SyncRequestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SyncRequestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SyncRequestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WsResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WsResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591